version: '3.11'
# version: '3.11'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - erp_backend_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: "False"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
    ports:
      - "8001:80"
    depends_on:
      - db
    networks:
      - erp_backend_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - db
    networks:
      - erp_backend_net
    volumes:
      - uploads_data:/app/uploads

volumes:
  db_data:
  uploads_data:


networks:
  erp_backend_net:
    driver: bridge
