import json
from datetime import datetime
from typing import Any, Optional

from fastapi import APIRouter, Depends, Form, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from db import get_db
from models.onboarding.asm_onboarding_models import AreaSalesManager
from models.onboarding.mr_onbooarding_models import MedicalRepresentative
from models.team.team_models import Team

router = APIRouter(prefix="/team", tags=["Team"])


class TeamResponseSchema(BaseModel):
	id: int
	team_id: int
	team_name: str
	team_description: Optional[str] = None
	whatsapp_group_link: Optional[str] = None
	team_leader_asm_id: str
	team_members_mr_ids: Optional[Any] = None
	created_at: datetime
	updated_at: datetime

	class Config:
		from_attributes = True


class TeamLeaderSchema(BaseModel):
	asm_id: str
	full_name: str
	phone_no: str


class TeamMemberSchema(BaseModel):
	mr_id: str
	full_name: str
	phone_no: str
	alt_phone_no: Optional[str] = None
	email: Optional[str] = None
	address: Optional[str] = None
	headquarter_assigned: Optional[str] = None
	territories_of_work: Optional[Any] = None
	profile_photo: Optional[str] = None


class TeamGetResponseSchema(TeamResponseSchema):
	team_leader: Optional[TeamLeaderSchema] = None
	team_members: list[TeamMemberSchema] = []


# Parse team member MR IDs from JSON or comma-separated input.
def _parse_team_members_json(team_members_mr_ids: Optional[str]) -> Optional[Any]:
	if team_members_mr_ids is None or team_members_mr_ids.strip() == "":
		return None
	try:
		return json.loads(team_members_mr_ids)
	except json.JSONDecodeError:
		members_list = [member.strip() for member in team_members_mr_ids.split(",") if member.strip()]
		return members_list if members_list else None


# Build enriched team response with ASM and MR details.
def _build_team_get_response(record: Team, db: Session) -> dict:
	team_leader = (
		db.query(AreaSalesManager)
		.filter(AreaSalesManager.asm_id == record.team_leader_asm_id)
		.first()
	)

	leader_payload = None
	if team_leader:
		leader_payload = {
			"asm_id": team_leader.asm_id,
			"full_name": team_leader.full_name,
			"phone_no": team_leader.phone_no,
		}

	member_ids = record.team_members_mr_ids if isinstance(record.team_members_mr_ids, list) else []
	members_payload: list[dict] = []
	if member_ids:
		members = db.query(MedicalRepresentative).filter(MedicalRepresentative.mr_id.in_(member_ids)).all()
		members_payload = [
			{
				"mr_id": member.mr_id,
				"full_name": member.full_name,
				"phone_no": member.phone_no,
				"alt_phone_no": member.alt_phone_no,
				"email": member.email,
				"address": member.address,
				"headquarter_assigned": member.headquarter_assigned,
				"territories_of_work": member.territories_of_work,
				"profile_photo": member.profile_photo,
			}
			for member in members
		]

	return {
		"id": record.id,
		"team_id": record.team_id,
		"team_name": record.team_name,
		"team_description": record.team_description,
		"whatsapp_group_link": record.whatsapp_group_link,
		"team_leader_asm_id": record.team_leader_asm_id,
		"team_members_mr_ids": record.team_members_mr_ids,
		"created_at": record.created_at,
		"updated_at": record.updated_at,
		"team_leader": leader_payload,
		"team_members": members_payload,
	}


@router.post("/post", response_model=TeamResponseSchema, status_code=status.HTTP_201_CREATED)
def create_team(
	team_name: str = Form(...),
	team_leader_asm_id: str = Form(...),
	team_members_mr_ids: Optional[str] = Form(None),
	team_description: Optional[str] = Form(None),
	whatsapp_group_link: Optional[str] = Form(None),
	db: Session = Depends(get_db),
):
	new_team = Team(
		team_name=team_name,
		team_description=team_description,
		whatsapp_group_link=whatsapp_group_link,
		team_leader_asm_id=team_leader_asm_id,
		team_members_mr_ids=_parse_team_members_json(team_members_mr_ids),
	)

	db.add(new_team)
	db.commit()
	db.refresh(new_team)

	# Keep team_id aligned with autogenerated numeric primary key.
	if new_team.team_id is None:
		new_team.team_id = new_team.id
		db.commit()
		db.refresh(new_team)

	return new_team


@router.get("/get-all", response_model=list[TeamGetResponseSchema])
def get_all_teams(db: Session = Depends(get_db)):
	records = db.query(Team).all()
	return [_build_team_get_response(record, db) for record in records]


@router.get("/get-by/{team_id}", response_model=TeamGetResponseSchema)
def get_team_by_team_id(team_id: int, db: Session = Depends(get_db)):
	record = db.query(Team).filter(Team.team_id == team_id).first()
	if not record:
		raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Team not found")
	return _build_team_get_response(record, db)


@router.get("/get-by-asm/{asm_id}", response_model=list[TeamGetResponseSchema])
def get_teams_by_asm_id(asm_id: str, db: Session = Depends(get_db)):
	records = db.query(Team).filter(Team.team_leader_asm_id == asm_id).all()
	if not records:
		raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No team found for the provided ASM ID")
	return [_build_team_get_response(record, db) for record in records]


# New endpoint: Get teams by MR ID
@router.get("/get-by-mr/{mr_id}", response_model=list[TeamGetResponseSchema])
def get_teams_by_mr_id(mr_id: str, db: Session = Depends(get_db)):
	from sqlalchemy import cast
	from sqlalchemy.dialects.postgresql import JSONB
	records = db.query(Team).filter(
		cast(Team.team_members_mr_ids, JSONB).contains([mr_id])
	).all()
	if not records:
		raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No team found for the provided MR ID")
	return [_build_team_get_response(record, db) for record in records]


@router.put("/update-by/{team_id}", response_model=TeamResponseSchema)
def update_team_by_team_id(
	team_id: int,
	team_name: Optional[str] = Form(None),
	team_description: Optional[str] = Form(None),
	whatsapp_group_link: Optional[str] = Form(None),
	team_leader_asm_id: Optional[str] = Form(None),
	team_members_mr_ids: Optional[str] = Form(None),
	db: Session = Depends(get_db),
):
	record = db.query(Team).filter(Team.team_id == team_id).first()
	if not record:
		raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Team not found")

	if team_name is not None:
		record.team_name = team_name
	if team_description is not None:
		record.team_description = team_description
	if whatsapp_group_link is not None:
		record.whatsapp_group_link = whatsapp_group_link
	if team_leader_asm_id is not None:
		record.team_leader_asm_id = team_leader_asm_id
	if team_members_mr_ids is not None:
		record.team_members_mr_ids = _parse_team_members_json(team_members_mr_ids)

	db.commit()
	db.refresh(record)
	return record


@router.delete("/delete-by/{team_id}", status_code=status.HTTP_200_OK)
def delete_team_by_team_id(team_id: int, db: Session = Depends(get_db)):
	record = db.query(Team).filter(Team.team_id == team_id).first()
	if not record:
		raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Team not found")

	db.delete(record)
	db.commit()
	return {"message": f"Team with id {team_id} deleted successfully"}
